version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: test_user
    #   MONGO_INITDB_ROOT_PASSWORD: test_pass
    ports:
      - "19000:27017"
    volumes:
      - mongodb_data:/data/db
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "17000:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonflydata:/data
volumes:
  dragonflydata:
    driver: local
  mongodb_data:
    driver: local