version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mg_vault_mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MG_MONGO_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MG_MONGO_PASSWORD}
    ports:
      - "19000:27017"
    volumes:
      - /app/mongo_data:/data/db
    networks:
      - mg_net
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: mg_vault_dragonfly
    ulimits:
      memlock: -1
    ports:
      - "17000:6379"
    volumes:
      - /app/dragonfly_data:/data
    networks:
      - mg_net
  backend:
    image: mgelios/mg_vault_backend:latest
    restart: always
    container_name: "mg_vault_backend"
    ports:
      - "443:443"
    networks:
      - mg_net
    volumes:
      - ${MG_VAULT_CERT_PATH}:${MG_VAULT_CERT_PATH}
      - ${MG_VAULT_KEY_PATH}:${MG_VAULT_KEY_PATH}
networks:
  mg_net:
    driver: bridge
volumes:
  dragonflydata:
    driver: local
  mongodb_data:
    driver: local